const $=s=>document.querySelector(s),box=$('#events'),q=$('#q'),regionEl=$('#region'),rewardEl=$('#reward'),gpsOnly=$('#gpsOnly');let events=[],selectedStatus='';
const today=()=>new Date().toISOString().slice(0,10);function state(e){let t=today();return t<e.schedule.startDate?'upcoming':t>e.schedule.endDate?'ended':'active'}const labels={active:'進行中',upcoming:'即將開始',ended:'已結束'};const icons={'特殊造型':'🎭','背卡':'🖼️','特殊背景':'🖼️','未知圖騰':'🔤','超極巨':'⚡','玩家裝飾':'👕','貼圖':'🏷️','其他':'🎁'};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const shinyName=x=>{let n=String(x.name||'').replace(/\s*✨+\s*/g,' ').trim();return esc(n)+(x.shiny?' ✨':'')};function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>x.classList.remove('show'),1200)}
function populate(){[...new Set(events.flatMap(e=>e.regions))].sort().forEach(x=>regionEl.insertAdjacentHTML('beforeend',`<option>${esc(x)}</option>`));[...new Set(events.flatMap(e=>e.specialRewards.map(r=>r.category)))].sort().forEach(x=>rewardEl.insertAdjacentHTML('beforeend',`<option>${esc(x)}</option>`))}
async function copyText(t,msg){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(t)}else{let x=document.createElement('textarea');x.value=t;x.setAttribute('readonly','');x.style.position='fixed';x.style.opacity='0';document.body.appendChild(x);x.select();x.setSelectionRange(0,x.value.length);if(!document.execCommand('copy'))throw new Error('copy failed');x.remove()}toast(msg)}catch(e){window.prompt('請長按複製以下網址：',t)}}function copyGps(lat,lng){copyText(lat+','+lng,'GPS 已複製')}function copyAll(id){let e=events.find(x=>x.id===id),a=e.locations.filter(x=>x.lat!=null).map(x=>x.name+' '+x.lat+','+x.lng);copyText(a.join('\n'),`已複製 ${a.length} 個 GPS`)}
function gpx(id){let e=events.find(x=>x.id===id),pts=e.locations.filter(x=>x.lat!=null);if(!pts.length)return;let xml='<?xml version="1.0" encoding="UTF-8"?>\n<gpx version="1.1" creator="pokemon-go-special-events" xmlns="http://www.topografix.com/GPX/1/1">\n'+pts.map(x=>`  <wpt lat="${x.lat}" lon="${x.lng}"><name>${esc(x.name)}</name></wpt>`).join('\n')+'\n</gpx>';let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([xml],{type:'application/gpx+xml'}));a.download=e.id+'.gpx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function order(a,b){let rank={active:0,upcoming:1,ended:2},d=rank[state(a)]-rank[state(b)];if(d)return d;return state(a)==='ended'?b.schedule.endDate.localeCompare(a.schedule.endDate):a.schedule.startDate.localeCompare(b.schedule.startDate)}
function render(){let s=q.value.trim().toLowerCase(),rg=regionEl.value,rw=rewardEl.value;let list=events.filter(e=>(!s||JSON.stringify(e).toLowerCase().includes(s))&&(!selectedStatus||state(e)===selectedStatus)&&(!rg||e.regions.includes(rg))&&(!rw||e.specialRewards.some(x=>x.category===rw))&&(!gpsOnly.checked||e.locations.some(x=>x.lat!=null))).sort(order);$('#summary').textContent=`顯示 ${list.length} / ${events.length} 個活動 · 進行中 ${events.filter(e=>state(e)==='active').length} · 即將開始 ${events.filter(e=>state(e)==='upcoming').length}`;$('#empty').hidden=!!list.length;box.innerHTML=list.map(e=>{let st=state(e),pts=e.locations.filter(x=>x.lat!=null);return `<article class="card"><div class="top"><div><h2><a class="titlelink" href="event.html?id=${encodeURIComponent(e.id)}">${esc(e.name)}</a></h2><div class="meta">📅 ${esc(e.schedule.startDate)} ～ ${esc(e.schedule.endDate)}</div><div class="meta">📍 ${e.regions.map(esc).join(' / ')}</div>${e.schedule.timeNote?`<div class="meta">🕒 ${esc(e.schedule.timeNote)}</div>`:''}</div><span class="badge ${st}">${labels[st]}</span></div><div class="rewards">${e.specialRewards.map(x=>`<span class="reward">${icons[x.category]||'🎁'} ${shinyName(x)} <small>· ${esc(x.category)}</small></span>`).join('')}</div><div class="cardfoot"><span class="meta">${pts.length?("GPS "+pts.length+" 點"):"GPS 未提供"}</span><a class="detailbtn" href="event.html?id=${encodeURIComponent(e.id)}">查看詳情 →</a></div>${e.notes?.length?`<p class="meta">${e.notes.map(esc).join('；')}</p>`:''}<div class="source">${e.sources.map((u,i)=>`<a href="${esc(u.url)}" target="_blank" rel="noopener">原始來源${e.sources.length>1?' '+(i+1):''}</a>`).join(' · ')}</div></article>`}).join('')}
fetch('./data/events.json').then(r=>r.json()).then(x=>{events=x;populate();render()}).catch(()=>{$('#empty').hidden=false;$('#empty').textContent='活動資料載入失敗'});[q,regionEl,rewardEl,gpsOnly].forEach(x=>x.addEventListener('input',render));$('#quick').addEventListener('click',e=>{if(!e.target.dataset.status&&e.target.dataset.status!=='')return;selectedStatus=e.target.dataset.status;document.querySelectorAll('#quick button').forEach(b=>b.classList.toggle('on',b===e.target));render()});
const copyCalendarUrl=$('#copyCalendarUrl'),calendarUrl=$('#calendarUrl');
copyCalendarUrl?.addEventListener('click',()=>copyText(calendarUrl.value,'ICS 訂閱網址已複製'));
