const $=s=>document.querySelector(s),box=$('#events'),q=$('#q'),regionEl=$('#region'),rewardMenu=$('#rewardMenu'),rewardSummary=$('#rewardSummary'),gpsOnly=$('#gpsOnly');let events=[],selectedStatus='',selectedRewards=new Set(),openGroup='active';
const today=()=>new Date().toISOString().slice(0,10),arr=x=>Array.isArray(x)?x:[],validDate=x=>/^\d{4}-\d{2}-\d{2}$/.test(String(x||''));function state(e){let t=today(),s=e?.schedule?.startDate,n=e?.schedule?.endDate;if(!validDate(s)||!validDate(n))return'unknown';return t<s?'upcoming':t>n?'ended':'active'}const labels={active:'進行中',upcoming:'即將開始',ended:'已結束',unknown:'日期待確認'};const icons={'特殊造型':'🎭','背卡':'🖼️','特殊背景':'🖼️','未知圖騰':'🔤','超極巨':'⚡','玩家裝飾':'👕','貼圖':'🏷️','其他':'🎁'};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const shinyName=x=>{let n=String(x?.name||'').replace(/\s*✨+\s*/g,' ').trim();return esc(n)+(x?.shiny?' ✨':'')};const dateText=e=>{let s=e?.schedule?.startDate,n=e?.schedule?.endDate;if(!validDate(s)||!validDate(n))return'日期待確認';return s===n?s:s+' ～ '+n};const estimated=e=>e?.schedule?.timeStatus==='estimated';function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>x.classList.remove('show'),1200)}
function populate(){[...new Set(events.flatMap(e=>arr(e.regions)).filter(Boolean))].sort().forEach(x=>regionEl.insertAdjacentHTML('beforeend',`<option>${esc(x)}</option>`));[...new Set(events.flatMap(e=>arr(e.specialRewards).map(r=>r?.category)).filter(Boolean))].sort().forEach(x=>rewardMenu.insertAdjacentHTML('beforeend',`<label><input type="checkbox" value="${esc(x)}"> <span>${esc(x)}</span></label>`))}
async function copyText(t,msg){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(t)}else{let x=document.createElement('textarea');x.value=t;x.setAttribute('readonly','');x.style.position='fixed';x.style.opacity='0';document.body.appendChild(x);x.select();x.setSelectionRange(0,x.value.length);if(!document.execCommand('copy'))throw new Error('copy failed');x.remove()}toast(msg)}catch(e){window.prompt('請長按複製以下內容：',t)}}function copyGps(lat,lng){copyText(lat+','+lng,'GPS 已複製')}function copyAll(id){let e=events.find(x=>x.id===id),a=arr(e?.locations).filter(x=>x?.lat!=null&&x?.lng!=null).map(x=>(x.name||'未命名地點')+' '+x.lat+','+x.lng);if(a.length)copyText(a.join('\n'),`已複製 ${a.length} 個 GPS`)}
function gpx(id){let e=events.find(x=>x.id===id),pts=arr(e?.locations).filter(x=>x?.lat!=null&&x?.lng!=null);if(!pts.length)return;let xml='<?xml version="1.0" encoding="UTF-8"?>\n<gpx version="1.1" creator="pokemon-go-special-events" xmlns="http://www.topografix.com/GPX/1/1">\n'+pts.map(x=>`  <wpt lat="${x.lat}" lon="${x.lng}"><name>${esc(x.name||'未命名地點')}</name></wpt>`).join('\n')+'\n</gpx>';let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([xml],{type:'application/gpx+xml'}));a.download=(e?.id||'event')+'.gpx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function order(a,b){let rank={active:0,upcoming:1,unknown:2,ended:3},sa=state(a),sb=state(b),d=rank[sa]-rank[sb];if(d)return d;let ad=a?.schedule?.[sa==='ended'?'endDate':'startDate']||'',bd=b?.schedule?.[sb==='ended'?'endDate':'startDate']||'';return sa==='ended'?bd.localeCompare(ad):ad.localeCompare(bd)}
function sourceHtml(e){let s=arr(e.sources);if(!s.length)return'<span>來源未提供</span>';return s.map((u,i)=>{let url=typeof u==='string'?u:u?.url,label='原始來源'+(s.length>1?' '+(i+1):'');return url?`<a href="${esc(url)}" target="_blank" rel="noopener">${label}</a>`:`<span>${label}：使用者提供圖片</span>`}).join(' · ')}
function dayDiff(from,to){let a=new Date(from+'T00:00:00Z'),b=new Date(to+'T00:00:00Z');return Math.ceil((b-a)/86400000)}
function countdown(e,st){let t=today(),s=e?.schedule?.startDate,n=e?.schedule?.endDate;if(!validDate(s)||!validDate(n))return'';if(st==='active'){let d=dayDiff(t,n);return d===0?'最後一天':`剩餘 ${d} 天`}if(st==='upcoming'){let d=dayDiff(t,s);return d===1?'明天開始':`${d} 天後`}return''}
function compactDate(e){let s=e?.schedule?.startDate,n=e?.schedule?.endDate;if(!validDate(s)||!validDate(n))return'日期待確認';return s===n?s:s+' ～ '+n}
function cardHtml(e){let st=state(e),pts=arr(e.locations).filter(x=>x?.lat!=null&&x?.lng!=null),regions=arr(e.regions),rewards=arr(e.specialRewards),cd=countdown(e,st);return `<article class="card compactcard"><a class="cardmain" href="event.html?id=${encodeURIComponent(e.id||'')}"><div class="compactbody"><div class="compacttitle"><h2>${estimated(e)?'⚠️ ':''}${esc(e.name||'未命名活動')}</h2><span class="badge ${st}">${labels[st]}</span></div><div class="compactmeta"><span>📅 ${esc(compactDate(e))}${estimated(e)?' · 暫定':''}</span><span>📍 ${regions.length?regions.map(esc).join(' / '):'地區未提供'}</span></div><div class="compactrewards">${rewards.length?rewards.slice(0,3).map(x=>`<span class="reward">${icons[x?.category]||'🎁'} ${shinyName(x)}</span>`).join(''):'<span class="meta">特殊獲取物未提供</span>'}${rewards.length>3?`<span class="moretag">+${rewards.length-3}</span>`:''}</div></div><div class="compactside">${cd?`<strong class="countdown ${st}">${cd}</strong>`:''}<span class="gpscount">${pts.length?'📍 '+pts.length:'GPS —'}</span><span class="chevron">›</span></div></a></article>`}
function render(){let s=q.value.trim().toLowerCase(),rg=regionEl.value;rewardSummary.textContent=selectedRewards.size?`特殊獲取物（${selectedRewards.size}）`:'全部特殊獲取物';let list=events.filter(e=>(!s||JSON.stringify(e).toLowerCase().includes(s))&&(!selectedStatus||state(e)===selectedStatus)&&(!rg||arr(e.regions).includes(rg))&&(!selectedRewards.size||[...selectedRewards].every(r=>arr(e.specialRewards).some(x=>x?.category===r)))&&(!gpsOnly.checked||arr(e.locations).some(x=>x?.lat!=null&&x?.lng!=null))).sort(order);$('#summary').textContent=`顯示 ${list.length} / ${events.length} 個活動 · 進行中 ${events.filter(e=>state(e)==='active').length} · 即將開始 ${events.filter(e=>state(e)==='upcoming').length}`;$('#empty').hidden=!!list.length;let groups=[['active','進行中'],['upcoming','即將開始'],['unknown','日期待確認'],['ended','已結束']];let visible=groups.filter(([st])=>list.some(e=>state(e)===st));if(!visible.some(([st])=>st===openGroup))openGroup=visible[0]?.[0]||'active';box.innerHTML=visible.map(([st,label])=>{let items=list.filter(e=>state(e)===st),open=st===openGroup;return `<details class="eventgroup ${st}" data-group="${st}" ${open?'open':''}><summary><span><i></i>${label} <b>(${items.length})</b></span><small>${open?'依日期排序':'點擊展開'}</small></summary><div class="groupcards">${items.map(cardHtml).join('')}</div></details>`}).join('')}
fetch('./data/events.json').then(r=>{if(!r.ok)throw 0;return r.json()}).then(x=>{events=Array.isArray(x)?x:[];populate();render()}).catch(()=>{$('#empty').hidden=false;$('#empty').textContent='活動資料載入失敗'});[q,regionEl,gpsOnly].forEach(x=>x?.addEventListener('input',render));rewardMenu?.addEventListener('change',e=>{if(e.target.matches('input[type=checkbox]')){e.target.checked?selectedRewards.add(e.target.value):selectedRewards.delete(e.target.value);render()}});$('#quick')?.addEventListener('click',e=>{if(!e.target.dataset.status&&e.target.dataset.status!=='')return;selectedStatus=e.target.dataset.status;document.querySelectorAll('#quick button').forEach(b=>b.classList.toggle('on',b===e.target));render()});
box?.addEventListener('click',e=>{let s=e.target.closest('.eventgroup>summary');if(!s||window.matchMedia('(max-width:800px)').matches)return;e.preventDefault();let d=s.parentElement;if(d.open)return;openGroup=d.dataset.group;render()});
const copyCalendarUrl=$('#copyCalendarUrl'),calendarUrl=$('#calendarUrl');copyCalendarUrl?.addEventListener('click',()=>copyText(calendarUrl.value,'ICS 訂閱網址已複製'));
